### ISSUE TITLE
Fail and success responses

### ISSUE THREAD

**Issue by xNoEndx** [mo-ah-dawood/my_fatoorah#4]
I'm currently testing your package with the test token (Which shows most/all payment gateways). Upon using the test cards, I always get the decline/fail transaction for less than 1 second then it disappear. I'm using you example code. Appreciate looking into it. Also is it possible to expose the transaction status as a response to be handled in app, rather than webview.

Thanks and much much appreciated.

Edit: I'm using version 2

**Comment by mo-ah-dawood** [comment]
For your first issue that you get the response for less than 1 second
that because we have to wait for call back url to be executed because in common this will do something
please don't use `finishAfterCallback` if you don't need to back immediately after execution if you use version 2.0.0
as for version 2.1.0 i replaced this property with another one called `afterPaymentBehaviour` its type is enum you can reach what you need by passing this value: `AfterPaymentBehaviour.BeforeCalbacksExecution`

for the second part the method `startPayment`  is future of  type bool => true for success and false for error , this for v2
as for v2.1 it will return `PaymentResponse`

**Comment by xNoEndx** [comment]
great! But another issue/change happened today. Yesterday when I use below code it would take me to benefit payment page (Using the test API), then after testing with the test cards. It would take me to the success/fail urls. Today it doesn't take me to the benefit payment gateway, only shows a Fatoorah invoice page with no payment way.

Screen: https://bit.ly/2WfsjiB

> MyFatoorah.startPayment(
                  context: context,
                  request: MyfatoorahRequest(
                    currencyIso: Country.Bahrain,
                    successUrl: "https://google.com",
                    errorUrl: "https://yahoo.com",
                    invoiceAmount: 100,
                    language: ApiLanguage.English,
                    token: null,
                    afterPaymentBehaviour: AfterPaymentBehaviour
                        .None, //See the describe for this property for more details
                  ),
                ).then((value) {
                  print(value.paymentId);
                  print(value.status);
                });

**Comment by mo-ah-dawood** [comment]
I think this issue in my fatoorah site
this is the generated url that will be redirected in webview
i tested it in chrome and have the same issue
`https://demo.myfatoorah.com/Ar/PayInvoice/Checkout?invoiceKey=0106212409235&paymentGatewayId=5`

try live account it may be test related issue
